server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh # payment_route   # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE     # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**            # 断言，路径相匹配的进行路由

        - id: payment_routh2 # payment_route  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE     # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**             # 断言，路径相匹配的进行路由


        - id: payment_routh3 # payment_route  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://news.baidu.com     # 匹配后提供服务的路由地址
          predicates:
            - Path=/guonei             # 断言，路径相匹配的进行路由
#            - After=2021-01-08T15:37:50.248+08:00[Asia/Shanghai] # 在此时间点之后生效
#            - Before=2121-01-08T15:37:50.248+08:00[Asia/Shanghai] # 在此时间点之前生效
#            - Between=2021-01-08T15:37:50.248+08:00[Asia/Shanghai], 2021-01-08T16:37:50.248+08:00[Asia/Shanghai]  #在此时间段内生效
#            - Cookie=username, lzw  #cookiename和值，用cookie的键、值去匹配，匹配上就执行路由
#            - Header=X-Request-Id, \d+  #请求头，用请求头包含的属性和属性的值去匹配，匹配上就执行路由。此处为请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Method=GET  #请求方式

eureka:
  instance:
    hostname: cloud-gateway-service   # 鼠标指到服务注册中心的微服务名后，在浏览器左下角显示的地址，若不配置，则默认显示localhost
    prefer-ip-address: true           # 左下角显示的地址，打开后会显示ip地址，覆盖上面设置的名字
    instance-id: gateway9527          # 在服务注册中心显示的主机名称，默认为主机名+application_name+端口号
  client:   # 服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

